@echo off
echo Installing Starship...
winget install starship
echo Installing PowerShell...
winget install --id Microsoft.Powershell --source winget
echo Installing gsudo...
winget install gsudo
refreshenv.bat
echo Running PowerShell Script...
pwsh.exe -ExecutionPolicy Bypass -Command ".\script.ps1"
